version: '3.9'
services:
    coordinator:
        container_name: coordinator
        build: ./coordinator
        ports:
            - '8080:8080'
        networks:
            - shardnet

    shard1:
        build: ./shard
        container_name: shard1
        environment:
            - ROLE=LEADER
            - PORT=8000
            - SHARD_ID=shardset-1
            - SHARD_NAME=shard1
            - ADDRESS=http://shard1:8000
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication1
        ports:
            - '8000:8000'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - shardnet

    shard2:
        build: ./shard
        container_name: shard2
        environment:
            - ROLE=FOLLOWER
            - PORT=8001
            - SHARD_ID=shardset-1
            - SHARD_NAME=shard2
            - ADDRESS=http://shard2:8001
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication1
        ports:
            - '8001:8001'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        volumes:
            - follower1-data:/app/data
        networks:
            - shardnet

    shard3:
        build: ./shard
        container_name: shard3
        environment:
            - ROLE=FOLLOWER
            - PORT=8002
            - SHARD_ID=shardset-1
            - SHARD_NAME=shard3
            - ADDRESS=http://shard3:8002
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication1
        ports:
            - '8002:8002'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        volumes:
            - follower2-data:/app/data
        networks:
            - shardnet

    shard4:
        build: ./shard
        container_name: shard4
        environment:
            - ROLE=LEADER
            - PORT=8003
            - SHARD_ID=shardset-2
            - SHARD_NAME=shard4
            - ADDRESS=http://shard4:8003
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication2
        ports:
            - '8003:8003'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        networks:
            - shardnet

    shard5:
        build: ./shard
        container_name: shard5
        environment:
            - ROLE=FOLLOWER
            - PORT=8004
            - SHARD_ID=shardset-2
            - SHARD_NAME=shard5
            - ADDRESS=http://shard5:8004
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication2
        ports:
            - '8004:8004'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        volumes:
            - follower1-data:/app/data
        networks:
            - shardnet

    shard6:
        build: ./shard
        container_name: shard6
        environment:
            - ROLE=FOLLOWER
            - PORT=8005
            - SHARD_ID=shardset-2
            - SHARD_NAME=shard6
            - ADDRESS=http://shard6:8005
            - COORDINATOR_URL=http://coordinator:8080/api/shards
            - RABBITMQ_URL=amqp://rabbitmq
            - EXCHANGE_NAME=replication2
        ports:
            - '8005:8005'
        depends_on:
            coordinator:
                condition: service_started
            rabbitmq:
                condition: service_healthy
        volumes:
            - follower2-data:/app/data
        networks:
            - shardnet

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - '5672:5672'
            - '15672:15672'
        healthcheck:
            test: ['CMD', 'rabbitmqctl', 'status']
            interval: 5s
            timeout: 3s
            retries: 5
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '512M'
        networks:
            - shardnet

    prometheus:
        image: prom/prometheus
        container_name: prometheus
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
            - prometheus-data:/prometheus
        ports:
            - '9090:9090'
        networks:
            - shardnet

    alertmanager:
        image: prom/alertmanager
        container_name: alertmanager
        volumes:
            - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
        ports:
            - '9093:9093'
        networks:
            - shardnet

    jaeger:
        image: jaegertracing/jaeger:2.0.0
        container_name: jaeger
        command:
            - '--set=receivers.otlp.protocols.grpc.endpoint=0.0.0.0:4317'
        ports:
            - '4317:4317'
            - '16686:16686'
        networks:
            - shardnet

    grafana:
        image: grafana/grafana
        container_name: grafana
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - ./monitoring/grafana:/var/lib/grafana
        depends_on:
            - prometheus
        networks:
            - shardnet

    n8n:
        image: n8nio/n8n
        container_name: n8n
        volumes:
            - C:\n8n:/home/node/.n8n
        ports:
            - '5678:5678'
        networks:
            - shardnet

volumes:
    follower1-data:
    follower2-data:
    prometheus-data:

networks:
    shardnet:
        driver: bridge
