name: Create artifacts and apply infrastructure

on:
    push:
        branches: [dev]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install coordinator deps
              run: npm ci
              working-directory: ./coordinator

            - name: Install shard deps
              run: npm ci
              working-directory: ./shard

            - name: Build coordinator
              run: npm run build
              working-directory: ./coordinator

            - name: Build shard
              run: npm run build
              working-directory: ./shard

            - name: Setup docker build
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push coordinator docker image
              uses: docker/build-push-action@v6
              with:
                  context: ./coordinator
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharding-coordinator:latest

            - name: Build and push shard image
              uses: docker/build-push-action@v6
              with:
                  context: ./shard
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sharding-shard:latest

    apply-infrastructure:
        runs-on: ubuntu-latest
        needs: build-and-push
        steps:
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Apply infrastructure
              uses: aws-actions/aws-cloudformation-github-deploy@v1
              with:
                  name: sharding-stack
                  template: ./cfn/infra.yaml
                  no-fail-on-empty-changeset: true
